/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classeGrafica;

import java.awt.Color;
import java.net.InetAddress;
import java.net.UnknownHostException;

/**
 *
 * @author rafael.anjos
 */
public class jFrameRead extends javax.swing.JFrame {

    private String serverIP;
    private String lojaOperation;
    private String segmentoUtil;

    /**
     * Creates new form jFrameRead2
     */
    public jFrameRead() {
        //      PARA SETAR A JANELA NO CENTRO DO DISPLAY
        this.setLocationRelativeTo(null);
        initComponents();
        statusCheckRede();
    }

    private void statusCheckRede() {
        String machineLocal = null, adressLocal = null;
        //      VERIFICA IP E NOME DA MÁQUINA
        try {
            machineLocal = InetAddress.getLocalHost().getHostName();
            System.out.println(machineLocal);
            machineHost.setText(machineLocal);
            adressLocal = InetAddress.getLocalHost().getHostAddress();
            System.out.println(adressLocal);

        } catch (UnknownHostException e) {
            System.out.println("Adaptador de Rede Ausente \n" + e);
        }

        if (!adressLocal.equals("127.0.0.1")) {
            statusNetword.setText("IP:" + adressLocal + "  CONECTADO!");
            //statusCheckServer(adressLocal);
        } else {
            statusNetword.setForeground(Color.red);
            statusNetword.setText("NÃO CONTECTADO!");
            segmento.setForeground(Color.BLUE);
            conectServer.setForeground(Color.BLUE);
            foundLoja.setForeground(Color.BLUE);
            segmento.setText("NÃO É POSSÍVEL SEGUIR!");
            conectServer.setText("NÃO É POSSÍVEL SEGUIR!");
            foundLoja.setText("NÃO É POSSÍVEL SEGUIR!");
        }
    }

    private void statusCheckServer(String Adress) {
        char adressIP[] = Adress.toCharArray();;
        String URLbank;
        String formaIpServer = "";
        int contaPonto = 0;
        for (int i = 0; i < adressIP.length; i++) {
//            System.out.println(""+adressIP[i]);
            if (adressIP[i] == '.') {
                contaPonto++;
//                System.out.println(formaIpServer);
            }
            if (contaPonto < 3) {
                formaIpServer = formaIpServer + "" + adressIP[i];
            }
        }
        conectServer.setText(formaIpServer+".");
        //System.out.println(formaIpServer);
        
        while(true){
            for(int i=108;i>101;i--){
            URLbank = "jdbc:mysql://"+formaIpServer+""+i+":3306/consinco";
                System.out.println("Pesquisando Servidor: "+i);              
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        segmento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        conectServer = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        statusNetword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        foundLoja = new javax.swing.JTextField();
        jPanelBaseSuperior = new javax.swing.JPanel();
        jPanelBseSuperior2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelBaseInferior = new javax.swing.JPanel();
        jPanelBaseInferior2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        machineHost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        segmento.setEditable(false);
        segmento.setBackground(new java.awt.Color(255, 255, 255));
        segmento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        segmento.setForeground(new java.awt.Color(0, 102, 0));
        segmento.setToolTipText("");
        segmento.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("SEGMENTO UTILIZADO:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CONEXÃO COM SERVIDOR:");

        conectServer.setEditable(false);
        conectServer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        conectServer.setForeground(new java.awt.Color(0, 102, 0));
        conectServer.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("STATUS CONEXÃO DE REDE:");

        statusNetword.setEditable(false);
        statusNetword.setBackground(new java.awt.Color(255, 255, 255));
        statusNetword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        statusNetword.setForeground(new java.awt.Color(0, 102, 0));
        statusNetword.setBorder(null);
        statusNetword.setOpaque(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("LOJA:");

        foundLoja.setEditable(false);
        foundLoja.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        foundLoja.setForeground(new java.awt.Color(0, 102, 0));
        foundLoja.setBorder(null);

        jPanelBaseSuperior.setBackground(new java.awt.Color(255, 102, 0));

        jPanelBseSuperior2.setBackground(new java.awt.Color(0, 153, 0));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Cooper Black BT", 2, 54)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Iniciando...");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelBseSuperior2Layout = new javax.swing.GroupLayout(jPanelBseSuperior2);
        jPanelBseSuperior2.setLayout(jPanelBseSuperior2Layout);
        jPanelBseSuperior2Layout.setHorizontalGroup(
            jPanelBseSuperior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBseSuperior2Layout.setVerticalGroup(
            jPanelBseSuperior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelBaseSuperiorLayout = new javax.swing.GroupLayout(jPanelBaseSuperior);
        jPanelBaseSuperior.setLayout(jPanelBaseSuperiorLayout);
        jPanelBaseSuperiorLayout.setHorizontalGroup(
            jPanelBaseSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBseSuperior2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBaseSuperiorLayout.setVerticalGroup(
            jPanelBaseSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseSuperiorLayout.createSequentialGroup()
                .addComponent(jPanelBseSuperior2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanelBaseInferior.setBackground(new java.awt.Color(255, 102, 0));

        jPanelBaseInferior2.setBackground(new java.awt.Color(0, 153, 0));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Cooper Black BT", 2, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Terminal de Consulta de Preço Supernorte");
        jLabel6.setToolTipText("");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelBaseInferior2Layout = new javax.swing.GroupLayout(jPanelBaseInferior2);
        jPanelBaseInferior2.setLayout(jPanelBaseInferior2Layout);
        jPanelBaseInferior2Layout.setHorizontalGroup(
            jPanelBaseInferior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBaseInferior2Layout.setVerticalGroup(
            jPanelBaseInferior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelBaseInferiorLayout = new javax.swing.GroupLayout(jPanelBaseInferior);
        jPanelBaseInferior.setLayout(jPanelBaseInferiorLayout);
        jPanelBaseInferiorLayout.setHorizontalGroup(
            jPanelBaseInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseInferior2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBaseInferiorLayout.setVerticalGroup(
            jPanelBaseInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBaseInferiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelBaseInferior2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("MAQUÍNA LOCAL: ");

        machineHost.setEditable(false);
        machineHost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        machineHost.setForeground(new java.awt.Color(0, 102, 0));
        machineHost.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaseSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelBaseInferior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(255, 255, 255))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(89, 89, 89)
                                .addComponent(machineHost, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(segmento)
                                    .addComponent(foundLoja, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                    .addComponent(conectServer))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statusNetword, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBaseSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(machineHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(statusNetword, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(conectServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(foundLoja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(segmento))
                .addGap(114, 114, 114)
                .addComponent(jPanelBaseInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameRead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameRead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameRead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameRead.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new jFrameRead().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField conectServer;
    private javax.swing.JTextField foundLoja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBaseInferior;
    private javax.swing.JPanel jPanelBaseInferior2;
    private javax.swing.JPanel jPanelBaseSuperior;
    private javax.swing.JPanel jPanelBseSuperior2;
    private javax.swing.JTextField machineHost;
    private javax.swing.JTextField segmento;
    private javax.swing.JTextField statusNetword;
    // End of variables declaration//GEN-END:variables

}
